---
# tasks file for packages

- name: "2.3.1 Ensure X11 server components are not installed (Automated)"
  ansible.builtin.package:
    name:
      - xserver-xorg-core
      - xserver-xorg
    state: absent

- name: "2.3.2 Ensure Avahi Server is not installed (Automated)"
  ansible.builtin.package:
    name: avahi-daemon
    state: absent

- name: "2.3.3 Ensure CUPS is not installed (Automated)"
  ansible.builtin.package:
    name: cupsd
    state: absent

- name: "2.3.4 Ensure DHCP Server is not installed (Automated)"
  ansible.builtin.package:
    name: isc-dhcp-server
    state: absent

- name: "2.3.5 Ensure LDAP server is not installed (Automated)"
  ansible.builtin.package:
    name: slapd
    state: absent

- name: "2.3.6 Ensure NFS is not installed (Automated)"
  ansible.builtin.package:
    name: nfs-kernel-server
    state: absent

- name: "2.3.7 Ensure DNS Server is not installed (Automated)"
  ansible.builtin.package:
    name: bind9
    state: absent

- name: "2.3.8 Ensure FTP Server is not installed (Automated)"
  ansible.builtin.package:
    name: vsftpd
    state: absent

- name: "2.3.9 Ensure HTTP server is not installed (Automated)"
  ansible.builtin.package:
    name: apache2
    state: absent

- name: "2.3.10 Ensure IMAP and POP3 server is not installed (Automated)"
  ansible.builtin.package:
    name: dovecot-imapd
    state: absent

- name: "2.3.11 Ensure Samba is not installed (Automated)"
  ansible.builtin.package:
    name: samba
    state: absent

- name: "2.3.12 Ensure HTTP Proxy Server is not installed (Automated)"
  ansible.builtin.package:
    name: squid
    state: absent

- name: "2.3.13 Ensure SNMP Server is not installed (Automated)"
  ansible.builtin.package:
    name: snmpd
    state: absent

- name: "2.3.14 Ensure NIS Server is not installed (Automated)"
  ansible.builtin.package:
    name: nis
    state: absent
