---
# tasks file for ssh

- name: "5.2.1 Set SSH LogLevel to INFO (Automated)"
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?LogLevel"
    line: "LogLevel INFO"
    notify: restart sshd

- name: "5.2.2 Set SSH MaxAuthTries to 4 (Automated)"
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?MaxAuthTries"
    line: "MaxAuthTries 4"
    notify: restart sshd

- name: "5.2.3 Disable root login via SSH (Automated)"
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"
    notify: restart sshd

- name: "5.2.4 Enable StrictModes in SSH (Automated)"
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?StrictModes"
    line: "StrictModes yes"
    notify: restart sshd

- name: "5.2.5 Disable SSH password authentication (Automated)"
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    notify: restart sshd

- name: "5.2.6 Disable SSH empty passwords (Automated)"
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PermitEmptyPasswords"
    line: "PermitEmptyPasswords no"
    notify: restart sshd

- name: "5.2.7 Set SSH ClientAliveInterval (Automated)"
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?ClientAliveInterval"
    line: "ClientAliveInterval 300"
    notify: restart sshd

- name: "5.2.8 Set SSH ClientAliveCountMax (Automated)"
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?ClientAliveCountMax"
    line: "ClientAliveCountMax 0"
    notify: restart sshd

- name: "5.2.9 Disable X11Forwarding in SSH (Automated)"
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?X11Forwarding"
    line: "X11Forwarding no"
    notify: restart sshd

- name: "5.2.10 Set SSH LoginGraceTime to 60 seconds (Automated)"
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?LoginGraceTime"
    line: "LoginGraceTime 60"
    notify: restart sshd

- name: "5.2.11 Use strong cryptographic algorithms (Automated)"
  ansible.builtin.blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Ciphers aes256-ctr,aes192-ctr,aes128-ctr
      MACs hmac-sha2-512,hmac-sha2-256
      KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256
    marker: "# {mark} ANSIBLE MANAGED BLOCK - STRONG CRYPTO"
    notify: restart sshd
