---
# tasks file for firewall

- name: "3.5.1.1 Ensure ufw is installed (Automated)"
  ansible.builtin.package:
    name: ufw
    state: present

- name: "3.5.1.2 Ensure ufw service is enabled (Automated)"
  ansible.builtin.service:
    name: ufw
    enabled: yes

- name: "3.5.2.1 Set ufw default deny policy (Automated)"
  ansible.builtin.ufw:
    direction: incoming
    policy: deny
  notify: reload ufw

- name: "3.5.2.2 Set ufw default deny policy for outgoing (Automated)"
  ansible.builtin.ufw:
    direction: outgoing
    policy: deny
  notify: reload ufw

- name: "3.5.2.3 Set ufw default deny policy for routed packets (Automated)"
  ansible.builtin.ufw:
    direction: routed
    policy: deny
  notify: reload ufw

- name: "Allow SSH connections"
  ansible.builtin.ufw:
    rule: allow
    to_port: "22"
    proto: tcp
  notify: reload ufw

- name: "Enable ufw"
  ansible.builtin.ufw:
    state: enabled
