---
# tasks file for kernel

- name: "3.1.1 Ensure IP forwarding is disabled (Automated)"
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: "0"
    sysctl_set: yes
    state: present
    reload: yes

- name: "3.1.2 Ensure packet redirect sending is disabled (Automated)"
  ansible.builtin.sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: "0"
    sysctl_set: yes
    state: present
    reload: yes

- name: "3.1.2 Ensure packet redirect sending is disabled for default (Automated)"
  ansible.builtin.sysctl:
    name: net.ipv4.conf.default.send_redirects
    value: "0"
    sysctl_set: yes
    state: present
    reload: yes

- name: "3.2.1 Ensure source routed packets are not accepted (Automated)"
  ansible.builtin.sysctl:
    name: net.ipv4.conf.all.accept_source_route
    value: "0"
    sysctl_set: yes
    state: present
    reload: yes

- name: "3.2.1 Ensure source routed packets are not accepted for default (Automated)"
  ansible.builtin.sysctl:
    name: net.ipv4.conf.default.accept_source_route
    value: "0"
    sysctl_set: yes
    state: present
    reload: yes

- name: "3.2.2 Ensure ICMP redirects are not accepted (Automated)"
  ansible.builtin.sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: "0"
    sysctl_set: yes
    state: present
    reload: yes

- name: "3.2.2 Ensure ICMP redirects are not accepted for default (Automated)"
  ansible.builtin.sysctl:
    name: net.ipv4.conf.default.accept_redirects
    value: "0"
    sysctl_set: yes
    state: present
    reload: yes

- name: "3.2.3 Ensure secure ICMP redirects are not accepted (Automated)"
  ansible.builtin.sysctl:
    name: net.ipv4.conf.all.secure_redirects
    value: "0"
    sysctl_set: yes
    state: present
    reload: yes

- name: "3.2.3 Ensure secure ICMP redirects are not accepted for default (Automated)"
  ansible.builtin.sysctl:
    name: net.ipv4.conf.default.secure_redirects
    value: "0"
    sysctl_set: yes
    state: present
    reload: yes

- name: "3.2.4 Ensure suspicious packets are logged (Automated)"
  ansible.builtin.sysctl:
    name: net.ipv4.conf.all.log_martians
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: "3.2.4 Ensure suspicious packets are logged for default (Automated)"
  ansible.builtin.sysctl:
    name: net.ipv4.conf.default.log_martians
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: "3.2.5 Ensure broadcast ICMP requests are ignored (Automated)"
  ansible.builtin.sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: "3.2.6 Ensure bogus ICMP responses are ignored (Automated)"
  ansible.builtin.sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: "3.2.7 Ensure Reverse Path Filtering is enabled (Automated)"
  ansible.builtin.sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: "3.2.7 Ensure Reverse Path Filtering is enabled for default (Automated)"
  ansible.builtin.sysctl:
    name: net.ipv4.conf.default.rp_filter
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: "3.2.8 Ensure TCP SYN Cookies is enabled (Automated)"
  ansible.builtin.sysctl:
    name: net.ipv4.tcp_syncookies
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
