---
# tasks file for users

- name: "5.3.1 Ensure password creation requirements are configured (Automated)"
  ansible.builtin.lineinfile:
    path: /etc/security/pwquality.conf
    regexp: "^{{ item.key }}"
    line: "{{ item.key }} = {{ item.value }}"
    create: yes
    mode: '0644'
  with_items:
    - { key: 'minlen', value: 14 }
    - { key: 'dcredit', value: -1 }
    - { key: 'ucredit', value: -1 }
    - { key: 'ocredit', value: -1 }
    - { key: 'lcredit', value: -1 }
    - { key: 'difok', value: 8 }

- name: "5.3.2 Ensure lockout for failed password attempts is configured (Automated)"
  ansible.builtin.lineinfile:
    path: /etc/security/faillock.conf
    regexp: "^deny ="
    line: "deny = 5"
    create: yes
    mode: '0644'

- name: "5.3.2 Add pam_faillock.so to system-auth (auth)"
  community.general.pamd:
    name: system-auth
    type: auth
    control: required
    module_path: pam_faillock.so
    module_arguments: "preauth silent audit deny=5 unlock_time=900"
    state: present

- name: "5.3.2 Add pam_faillock.so to system-auth (account)"
  community.general.pamd:
    name: system-auth
    type: account
    control: required
    module_path: pam_faillock.so
    state: present

- name: "5.3.3 Ensure password expiration is 365 days or less (Automated)"
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: "^PASS_MAX_DAYS"
    line: "PASS_MAX_DAYS 365"

- name: "5.3.4 Ensure minimum days between password changes is 7 or more (Automated)"
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: "^PASS_MIN_DAYS"
    line: "PASS_MIN_DAYS 7"

- name: "5.3.5 Ensure password expiration warning days is 7 or more (Automated)"
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: "^PASS_WARN_AGE"
    line: "PASS_WARN_AGE 7"

- name: "5.2.4 Ensure root login is disabled (Automated)"
  ansible.builtin.user:
    name: root
    password_lock: yes

- name: "5.4.4 Ensure default user umask is 027 or more restrictive (Automated)"
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: "^UMASK"
    line: "UMASK 027"

- name: "5.5 Ensure inactive password lock is 30 days or less (Automated)"
  ansible.builtin.user:
    name: "{{ item.user }}"
    expires: "{{ (ansible_date_time.epoch | int) + 2592000 }}"
  with_items:
    - "{{ ansible_users_with_shells }}"



- name: "Configure passwordless sudo for specified users"
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/99-passwordless-{{ item }}"
    line: "{{ item }} ALL=(ALL) NOPASSWD: ALL"
    create: yes
    validate: /usr/sbin/visudo -cf %s
    mode: '0440'
  with_items: "{{ passwordless_sudo_users }}"


